using System;

namespace WindowsShell.Nspace
{
	public enum Shell32Icon
	{
		None			= 0,
		BlankDocument	= -1,
		Document		= -2,
		Application		= -3,
		Folder			= -4,
		OpenFolder		= -5,
		FloppyDrive		= -7,
		RemovableDrive	= -8,
		HardDrive		= -9,
		NetworkDrive	= -10,
		NetworkDriveDisconnected = -11,
		CdRomDrive		= -12,
		EntireNetwork	= -14,
		Network			= -15,
		MyComputer		= -16,
		Printer			= -17,
		MyNetworkPlaces	= -18,
		Workgroup		= -19,
		FolderView		= -20,
		MyRecentDocuments = -21,
		ControlPanel	= -22,
		Find			= -23,
		Help			= -24,
		Run				= -25,
		DeviceRemoval	= -27,
		TurnOffComputer = -28,
		ShareOverlay	= -29,
		ShortcutOverlay	= -30,
		TimeOverlay		= -31,
		RecycleBinEmpty	= -32,
		RecycleBinFull	= -33,
		DialUpNetworking = -34,
		Desktop			= -35,
		Fonts			= -39,
		StartMenu		= -40,
		MusicCd			= -41,
		Favourites		= -44,
		LogOff			= -45,
		WindowsExplorer	= -46,
		WindowsUpdate	= -47,
		Padlock			= -48,
		Blank			= -50,
		ExplorerFind	= -134,
		PrintersFolder	= -138,
		AddPrinter		= -139,
		NetworkPrinter	= -140,
		FilePrinter		= -141,
		Replace			= -146,
		InfFile			= -151,
		TxtFile			= -152,
		CmdFile			= -153,
		DllFile			= -154,
		FonFile			= -155,
		TtfFile			= -156,
		AdobeFontFile	= -157,
		Backup			= -165,
		DiskDefragmenter = -167,
		DefaultPrinter	= -168,
		DefaultNetworkPrinter = -169,
		DefaultFilePrinter = -170,
		NetworkFolder	= -172,
		NetworkConnections = -175,
		AddNetworkFolder = -176,
		AddEntireNetwork = -178, // ???
		ShowCommonTasks	= -182,
		WindowsClassicFolders = -183,
		OpenEachFolderInTheSameWindow = -184,
		OpenEachFolderInItsOwnWindow = -185,
		SingleClickToOpenAnItem = -186,
		DoubleClickToOpenAnItem	= -187,
		Fax				= -196,
		DefaultFax		= -197,
		DefaultNetworkFax = -198,
		NetworkFax		= -199,
		FolderOptions	= -210
		/* and more */
	}
}
